version: '3.4'

services:
  products:
    build:
      context: ./ProductsMicroservice
      dockerfile: Dockerfile
    ports:
      - "5000:80"

  orders:
    build:
      context: ./OrdersMicroservice
      dockerfile: Dockerfile
    ports:
      - "5001:80"